"""GitHub PR integration — posts agent artifacts as PR comments."""

import logging
import subprocess
from pathlib import Path

from models.artifact import ArtifactBundle

logger = logging.getLogger(__name__)


def format_pr_comment(
    bundle: ArtifactBundle,
    artifact_url: str = "",
) -> str:
    """Format a PR comment with agent demo results."""
    lines: list[str] = []

    lines.append("## 🤖 Agent Demo Video")
    lines.append("")

    if bundle.summary:
        lines.append(bundle.summary)
        lines.append("")

    if bundle.video_path:
        lines.append("### 🎬 Demo Video")
        if artifact_url:
            lines.append(f"**[Download demo video]({artifact_url})** (see Artifacts section)")
        else:
            lines.append(f"Video: `{bundle.video_path}`")
        lines.append("")

    if bundle.screenshot_paths:
        lines.append(f"### 📸 Screenshots ({len(bundle.screenshot_paths)})")
        lines.append("")
        for i, ss in enumerate(bundle.screenshot_paths):
            name = Path(ss).stem
            lines.append(f"**{i + 1}. {name}**")
        lines.append("")

    if bundle.log_text:
        lines.append("<details>")
        lines.append("<summary>📋 Agent Log</summary>")
        lines.append("")
        lines.append("```")
        # Truncate logs to avoid giant comments
        log_lines = bundle.log_text.strip().splitlines()
        if len(log_lines) > 50:
            lines.extend(log_lines[:25])
            lines.append(f"... ({len(log_lines) - 50} lines omitted) ...")
            lines.extend(log_lines[-25:])
        else:
            lines.extend(log_lines)
        lines.append("```")
        lines.append("</details>")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by PR Video Agent | Demos, not diffs*")

    return "\n".join(lines)


def post_pr_comment(
    repo: str,
    pr_number: int,
    comment: str,
) -> bool:
    """Post a comment on a GitHub PR using the gh CLI."""
    try:
        result = subprocess.run(
            ["gh", "pr", "comment", str(pr_number), "--repo", repo, "--body", comment],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            logger.error(
                "Failed to post PR comment",
                extra={"returncode": result.returncode, "stderr": result.stderr[:200]},
            )
            return False
        logger.info("PR comment posted", extra={"repo": repo, "pr": pr_number})
        return True
    except FileNotFoundError:
        logger.error("gh CLI not found — install GitHub CLI to post PR comments")
        return False
    except subprocess.TimeoutExpired:
        logger.error("PR comment posting timed out")
        return False
