"""Data models for the cloud agent system. Leaf layer — no project imports."""

from dataclasses import dataclass, field
from enum import Enum


class AgentStatus(Enum):
    """Status of an agent session."""

    PENDING = "pending"
    PLANNING = "planning"
    BUILDING = "building"
    INTERACTING = "interacting"
    RECORDING = "recording"
    COLLECTING = "collecting"
    COMPLETE = "complete"
    FAILED = "failed"


class StepType(Enum):
    """Type of browser interaction step."""

    NAVIGATE = "navigate"
    CLICK = "click"
    TYPE = "type"
    SCROLL = "scroll"
    WAIT = "wait"
    SCREENSHOT = "screenshot"
    ASSERT_TEXT = "assert_text"
    ASSERT_VISIBLE = "assert_visible"


class AgentActionType(Enum):
    """Type of high-level agent action."""

    ANALYZE_DIFF = "analyze_diff"
    BUILD_APP = "build_app"
    START_SERVER = "start_server"
    GENERATE_PLAN = "generate_plan"
    EXECUTE_PLAN = "execute_plan"
    RUN_TESTS = "run_tests"
    COLLECT_ARTIFACTS = "collect_artifacts"


@dataclass
class InteractionStep:
    """A single browser interaction step."""

    step_type: StepType
    target: str = ""
    selector: str = ""
    value: str = ""
    description: str = ""
    timeout_ms: int = 5000


@dataclass
class InteractionPlan:
    """A sequence of browser interaction steps generated by the agent."""

    steps: list[InteractionStep] = field(default_factory=list)
    description: str = ""
    expected_outcome: str = ""


@dataclass
class AgentAction:
    """A recorded action taken by the agent during a session."""

    action_type: AgentActionType
    description: str = ""
    result: str = ""
    error: str = ""
    duration_seconds: float = 0.0


@dataclass
class AgentSession:
    """Full state of an agent session."""

    session_id: str
    repo_url: str = ""
    pr_number: int = 0
    diff: str = ""
    app_url: str = ""
    status: AgentStatus = AgentStatus.PENDING
    actions: list[AgentAction] = field(default_factory=list)
    interaction_plan: InteractionPlan | None = None
    error: str = ""
    container_id: str = ""
